stages:
  - build
  - deploy

build:
  stage: build
  image: docker:dind
  script:
    - /usr/local/bin/dockerd &
    - docker -H unix:///var/run/docker.sock login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker -H unix:///var/run/docker.sock build --tag $CI_REGISTRY_IMAGE:builder-$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker -H unix:///var/run/docker.sock push $CI_REGISTRY_IMAGE:builder-$CI_COMMIT_SHA
    - docker -H unix:///var/run/docker.sock push $CI_REGISTRY_IMAGE:latest
  only:
    - develop
  tags:
    - docker

deploy:
  stage: deploy
  variables:
    JOB_NAME: "onlineballpointgame-dev"
    ENDPOINT_URL: "ballpointgame.apps.openforce.com"
    GA_TRACKING_ID: "UA-178259325-2"
  script:
    # Check job's ref name
    - echo $CI_COMMIT_REF_NAME
    # and is this ref protected
    - echo $CI_COMMIT_REF_PROTECTED
    - chmod +x onlineballpointgame.nomad.sh
    - ./onlineballpointgame.nomad.sh > onlineballpointgame.nomad
    - nomad job run onlineballpointgame.nomad
  only:
    - develop
  tags:
    - bastion
    - nomad
    - vault

deploy_prod:
  stage: deploy
  variables:
    JOB_NAME: "onlineballpointgame-prod"
    ENDPOINT_URL: "remoteballpointgame.openforce.com"
    GA_TRACKING_ID: "UA-178259325-1"
  script:
    # Check job's ref name
    - echo $CI_COMMIT_REF_NAME
    # and is this ref protected
    - echo $CI_COMMIT_REF_PROTECTED
    - chmod +x onlineballpointgame.nomad.sh
    - ./onlineballpointgame.nomad.sh > onlineballpointgame.nomad
    - nomad job run onlineballpointgame.nomad
  only:
    - master
  when: manual
  tags:
    - bastion
    - nomad
    - vault
