stages:
  - deploy
  - stop


deploy_job:
  stage: deploy
  resource_group: staging
  tags:
    - ballpointgame
  only:
    - /^master$/
  script:
    - docker build -t onlineballpointgame -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH -t latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker stop $(docker ps -q -f "label=onlineballpointgame") || true
    - docker rm onlineballpointgame || true
    - docker run -d --label "onlineballpointgame" --name "onlineballpointgame" -p 5000:5000 onlineballpointgame


stop_job:
  stage: stop
  resource_group: staging
  tags:
    - ballpointgame
  when: manual
  script:
    - docker stop $(docker ps -q -f "label=onlineballpointgame") || true