stages:
  - build
  - deploy

variables:
  CONTAINER_STAGING_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA

build:
  stage: build
  image: docker:dind
  script:
    - /usr/local/bin/dockerd &
    - docker -H unix:///var/run/docker.sock login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker -H unix:///var/run/docker.sock build --tag $CONTAINER_STAGING_TAG .
    - docker -H unix:///var/run/docker.sock push $CONTAINER_STAGING_TAG
  tags:
    - "cloud2-docker"

deploy:
  stage: deploy
  environment:
    name: staging
  variables:
    JOB_NAME: "onlineballpointgame-dev"
    STAGE: "dev"
    ENDPOINT_URL: "ballpointgame.apps.openforce.com"
  script:
    # Check job's ref name
    - echo $CI_COMMIT_REF_NAME
    # and is this ref protected
    - echo $CI_COMMIT_REF_PROTECTED
    - echo $GA_TRACKING_ID
    - export NOMAD_ADDR=https://nomad.service.consul:4646
    - export NOMAD_CACERT=/etc/hashi/nomad-ca.pem
    - export NOMAD_CLIENT_CERT=/etc/hashi/nomad-cli.pem
    - export NOMAD_CLIENT_KEY=/etc/hashi/nomad-cli-key.pem
    - chmod +x onlineballpointgame.nomad.sh
    - ./onlineballpointgame.nomad.sh > onlineballpointgame.nomad
    - nomad job run onlineballpointgame.nomad
  only:
    - develop
  tags:
    - "cloud2-shell"

deploy_prod:
  stage: deploy
  environment:
    name: prod
  variables:
    JOB_NAME: "onlineballpointgame-prod"
    STAGE: "prod"
    ENDPOINT_URL: "remoteballpointgame.openforce.com"
  script:
    # Check job's ref name
    - echo $CI_COMMIT_REF_NAME
    # and is this ref protected
    - echo $CI_COMMIT_REF_PROTECTED
    - echo $GA_TRACKING_ID
    - export NOMAD_ADDR=https://nomad.service.consul:4646
    - export NOMAD_CACERT=/etc/hashi/nomad-ca.pem
    - export NOMAD_CLIENT_CERT=/etc/hashi/nomad-cli.pem
    - export NOMAD_CLIENT_KEY=/etc/hashi/nomad-cli-key.pem
    - chmod +x onlineballpointgame.nomad.sh
    - ./onlineballpointgame.nomad.sh > onlineballpointgame.nomad
    - nomad job run onlineballpointgame.nomad
  only:
    - master
  when: manual
  tags:
    - "cloud2-shell"
