stages:
  - build
  - deploy
  - stop

build:
  stage: build
  image: docker:dind
  script:
    - /usr/local/bin/dockerd &
    - docker -H unix:///var/run/docker.sock login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker -H unix:///var/run/docker.sock build --tag $CI_REGISTRY_IMAGE:builder-$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker -H unix:///var/run/docker.sock push $CI_REGISTRY_IMAGE:builder-$CI_COMMIT_SHA
    - docker -H unix:///var/run/docker.sock push $CI_REGISTRY_IMAGE:latest
  only:
    - develop
  tags:
    - docker

deploy:
  stage: deploy
  variables:
    ENDPOINT_URL: "ballpointgame.apps.openforce.com"
  script:
    # Check job's ref name
    - echo $CI_COMMIT_REF_NAME
    # and is this ref protected
    - echo $CI_COMMIT_REF_PROTECTED
    - chmod +x onlineballpointgame.nomad.sh
    - ./onlineballpointgame.nomad.sh > onlineballpointgame.nomad
    - nomad job run onlineballpointgame.nomad
  only:
    - develop
  tags:
    - bastion
    - nomad
    - vault

deploy_prod:
  stage: deploy
  script:
    # Check job's ref name
    - echo $CI_COMMIT_REF_NAME
    # and is this ref protected
    - echo $CI_COMMIT_REF_PROTECTED
    - chmod +x onlineballpointgame.nomad.sh
    - ./onlineballpointgame.nomad.sh > onlineballpointgame.nomad
    - nomad job run onlineballpointgame.nomad
  only:
    - master
  when: manual
  tags:
    - bastion
    - nomad
    - vault

deploy_job:
  stage: deploy
  resource_group: staging
  tags:
    - ballpointgame
  only:
    - /^master$/
  script:
    - echo "ANALYTICS_KEY=$ANALYTICS_KEY"
    - docker build --build-arg "ANALYTICS_KEY=$ANALYTICS_KEY" -t onlineballpointgame -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH -t $CI_REGISTRY_IMAGE:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker stop $(docker ps -q -f "label=onlineballpointgame") || true
    - docker rm onlineballpointgame || true
    - docker run -d --label "onlineballpointgame" --name "onlineballpointgame" -p 5000:5000 onlineballpointgame


stop_job:
  stage: stop
  resource_group: staging
  tags:
    - ballpointgame
  when: manual
  script:
    - docker stop $(docker ps -q -f "label=onlineballpointgame") || true